# Generated by Django 4.2.11 on 2024-05-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Category",),
        migrations.RenameField(
            model_name="medicine", old_name="aciklama", new_name="description",
        ),
        migrations.RemoveField(model_name="medicine", name="anasayfa",),
        migrations.RemoveField(model_name="medicine", name="ilac_adi",),
        migrations.RemoveField(model_name="medicine", name="resim",),
        migrations.AddField(
            model_name="medicine",
            name="name",
            field=models.CharField(default="Unknown Medicine", max_length=100),
        ),
        migrations.AddField(
            model_name="medicine",
            name="photo",
            field=models.ImageField(
                default="medicines/static/img/1.jpg", upload_to="medicines/static/img"
            ),
        ),
    ]
