# Generated by Django 4.2.11 on 2024-05-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "medicines",
            "0002_delete_category_rename_aciklama_medicine_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
