# Generated by Django 4.2.11 on 2024-05-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0004_medicine_category_alter_medicine_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("photo", models.ImageField(upload_to="img")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
